name: .NET Tests & CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest  

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0'

    - name: Restore dependencies
      run: dotnet restore duAnPro/duAnPro.sln

    - name: Build project
      run: dotnet build duAnPro/duAnPro.sln --configuration Release

    - name: Run unit tests
      run: dotnet test duAnPro/Test/TestProject/TestProject.csproj --no-build --logger "trx;LogFileName=test_results.trx"

    - name: Upload test results
      uses: actions/upload-artifact@v4
      with:
        name: Test Results
        path: duAnPro/TestResults/test_results.trx
